# Autogenerated wrapper script for ParseGen_jll for i686-w64-mingw32-cxx11
export libparsegen, parsegen_calc

JLLWrappers.@generate_wrapper_header("ParseGen")
JLLWrappers.@declare_library_product(libparsegen, "libparsegen.dll")
JLLWrappers.@declare_executable_product(parsegen_calc)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libparsegen,
        "bin\\libparsegen.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        parsegen_calc,
        "bin\\parsegen-calc.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
