# Autogenerated wrapper script for ParseGen_jll for x86_64-apple-darwin
export libparsegen, parsegen_calc

JLLWrappers.@generate_wrapper_header("ParseGen")
JLLWrappers.@declare_library_product(libparsegen, "@rpath/libparsegen.dylib")
JLLWrappers.@declare_executable_product(parsegen_calc)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libparsegen,
        "lib/libparsegen.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        parsegen_calc,
        "bin/parsegen-calc",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
